import Head from 'next/head'
import Header from "../components/Header"
import Banner from '@/components/Banner'
import Smallcards from '@/components/Smallcards'
import Mediumcards  from '@/components/Mediumcards'
import Largecard  from '@/components/Largecard'
import Footer from '@/components/Footer'

export default function Home({explore_data,cards_data }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <Banner/>

      <main className='max-w-7xl mx-auto px-8 sm:px-16'>
        <section className="pt-6">
          <h2 className='text-4xl font-semibold pb-5'>
            Explore Nearby
          </h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
          {explore_data?.map((item) => {
            return <Smallcards 
            key={item.img}
            img={item.img}
            distance={item.distance}
            location={item.location}
             />
             })}
          </div>
        </section>

        <section>
          <h2 className='text-4xl font-semibold py-7'>Live Anywhere</h2>

          <div id='card' className='flex space-x-3 overflow-scroll'>
             
          {cards_data?.map(item => (
            <Mediumcards
            key={item.img}
            img={item.img}
            title={item.title}
            />
          )) }

          </div>

        </section>

        <Largecard
        img='https://links.papareact.com/4cj'  
        title='The Greatest Outdoors'
        description='Wishlists curated by Airbnb'
        buttonText='Get Inspired'
        />

        <Footer/>

      

      </main>
      
   </div>
  );
}

export async function getStaticProps() {
  const explore_data = await fetch('https://www.jsonkeeper.com/b/4G1G')
  .then((res) => res.json());

  const cards_data = await fetch('https://www.jsonkeeper.com/b/VHHT')
  .then((res) => res.json());

  return {
    props:{
      explore_data,
      cards_data
    }
  }
}